### ISSUE TITLE
Revamp wording

### ISSUE THREAD

**Issue by drahnr** [paritytech/cachepot#132]
Currently we are having trouble / overlapping meaning of `server`. After all the local `cachepot` launches a command server. In `dist` mode we also have `scheduler` and `server`.

I propose to rename as follows:

`scheduler` -> `scheduler`
`(client) server` -> `connector`
`(dist) scheduler` -> `scheduler`
`(dist) server` -> `worker`

This would simplify onboarding people and detaching the functional semantics from the process naming and simplify writing coherent documentation.

**Comment by Xanewok** [comment]
That's a good idea! I've been confused very often wrt local and dist build servers.

I very much like the idea of renaming `(dist) build server -> (dist) worker`. I think it more clearly conveys that it's one of many most of the time and it does the actual work. Big 👍

I'm not sold on connector though - in the dist case it really is the connector but other than that it's a daemon that also coordinates builds and caches/fetches the result. Maybe something like `coordinator (daemon)` would be more fitting?

**Comment by drahnr** [comment]
:+1: for `coordinator`

**Comment by montekki** [comment]
Done in #134
