### ISSUE TITLE
cargo build fails with "cachepot: error: Timed out waiting for coordinator startup"

### ISSUE THREAD

**Issue by claudiociardelli** [paritytech/cachepot#150]
I get this error when running cargo build --release

`error: failed to run "rustc" to learn about target-specific information

Caused by:
  process didn't exit successfully: "/home/toto/.cargo/bin/cachepot rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg" (exit status: 2)
  --- stderr
  cachepot: error: Timed out waiting for coordinator startup`

**Comment by Xanewok** [comment]
What's your environment and what package were you trying to compile?

Can you try running `cachepot --stop-coordinator` and re-running the compilation again?

**Comment by digitalillusion** [comment]
I had to reinstall after `cachepot --stop-coordinator`

`cargo install --git https://github.com/paritytech/cachepot`

then issue disappeared

**Comment by Xanewok** [comment]
That's good! Closing this, then
