### ISSUE TITLE
move away from ` rouille`

### ISSUE THREAD

**Issue by drahnr** [paritytech/cachepot#39]
Currently `rouille` is used which is heavily thread based, there is an upstream effort to move to `actix-web`, but I am not sure this is what we want. https://github.com/mozilla/sccache/issues/742#issuecomment-808824589

Evaluate alternative crates to replace `rouille`:

* [ ] `actix-web`
* [ ] `hyper`
* [ ] `tide`
* [ ] ...

**Comment by aidanhs** [comment]
An important evaluation criteria is to find something that supports https certificates (some libraries opt to defer that to something like nginx) so that builders can generate and use them on the fly.

**Comment by drahnr** [comment]
Thanks for the hint, we are just about to get started discussing alternatives to `rouille` after attempting to get #31 upstream.

**Comment by fourbytes** [comment]
[Axum](https://github.com/tokio-rs/axum) might be an option too.
