### ISSUE TITLE
Future plans: prefilling local cache

### ISSUE THREAD

**Issue by gww-parity** [paritytech/cachepot#46]
Mechanism to prefill local cache.

Use case: instance with `sscache server` may have a lot of artifacts alredy compiled over night. Why not make it possible to precache it ,e.g. during making morning tea? For that torrent protocol could be used, so once all users start fetching at same day, it fetches even faster :).

**Comment by Xanewok** [comment]
That seems like an overkill; if we'll run the nightly builds as part of the CI, then the resulting artifacts should be saved already on a bucket/storage that's ideally also shared with the developers (if only in read-only mode). Sharing the artifacts in a P2P manner is something that's orthogonal to this but also a very interesting idea (for a cachepot 3.0 :grin: )

@drahnr do you think we can close this for now?

**Comment by drahnr** [comment]
Yeah, complexity vs gain is in an unreasonable relationship.

The first compilation run will also do the same, just more effectively. And if the kV store is the bottleneck, tiered caching will remedy that as well.
